### ISSUE TITLE
Support `Refine[]`

### ISSUE THREAD

**Issue by aravindh-krishnamoorthy** [Mathics3/mathics-core#1230]
Support `Refine[]` Wolfram language function described here: [Refine](https://reference.wolfram.com/language/ref/Refine.html.en). 

`Refine[]` is different and (usually) lightweight compared to `Simplify[]` and `FullSimplify[]` and only performs reductions based on global assumptions and those passed to the function.

**Is your feature request related to a problem? Please describe.**
`Refine[]` is used in Rubi (https://github.com/Mathics3/Mathics3-Rubi/).

**Describe the solution you'd like**
Support `Refine[]` Wolfram language function described here: [Refine](https://reference.wolfram.com/language/ref/Refine.html.en).

**Describe alternatives you've considered**
In Rubi, `Refine[]` is currently equated to `Simplify[]`.

**Additional context**
Sympy version of `Refine[]` is here: https://docs.sympy.org/latest/modules/assumptions/refine.html, which might likely be of help to the implementor.

**Comment by ricor07** [comment]
Hello, I'd like to join the project by working on this issue.

**Comment by rocky** [comment]
Hi @ricor07 .  I would love for you to help by working on this issue.  

I wrote  https://mathics-development-guide.readthedocs.io/en/latest/extending/developing-code/extending/tutorial.html hoping to help people get started in this kind of activity. Please read that and the broader section on extending Mathics3.

If you have any questions as you go a long let me know.

**Comment by rocky** [comment]
@ricor07 As a warmup to doing this function, you might consider doing #1187.  I believe this is a straightforward process of wrapping a SymPy function into a Mathics3 function. In doing this, you'd practice the boilerplate part of what is needed to add a new builtin function. And this too will eventually be needed by Rubi.

**Comment by ricor07** [comment]
Good morning. I can't use your repo. After running this commands:

```git clone https://github.com/Mathics3/mathics-core.git
cd mathics-core
python -m venv venv
venv\Scripts\activate
pip install -e .
mathics```

This is what I get:
```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\angel\mathics-core\venv\Scripts\mathics.exe\__main__.py", line 4, in <module>
  File "C:\Users\angel\mathics-core\mathics\main.py", line 24, in <module>
    from mathics.builtin.trace import TraceBuiltins, traced_apply_function
  File "C:\Users\angel\mathics-core\mathics\builtin\trace.py", line 28, in <module>
    from mathics.core.builtin import Builtin
  File "C:\Users\angel\mathics-core\mathics\core\builtin.py", line 32, in <module>
    import mathics.core.parser.operators
  File "C:\Users\angel\mathics-core\mathics\core\parser\__init__.py", line 21, in <module>
    from mathics.core.parser.operators import all_operator_names
  File "C:\Users\angel\mathics-core\mathics\core\parser\operators.py", line 25, in <module>
    assert osp.exists(
AssertionError: Internal error: Mathics3 Operator information are missing; expected to be in C:\Users\angel\mathics-core\mathics\data\operator-tables.json
```

I am on Windows.

**Comment by rocky** [comment]
When building from git source in the master branch,  we now need to generate JSON operator tables. This is done on POSIX systems that have bash using `admin-tools/make-op-tables`. But this is just running some Python programs that should be installed when you install mathics-scanner. These programs are `mathics3-generate-json-table`  and `mathics3-generate-operator-json-table`. 

To run from a command line: 

```
chdir <place where mathics/data exists>
mathics3-generate-json-table \
    --field=ascii-operator-to-symbol \
    --field=ascii-operator-to-unicode \
    --field=ascii-operator-to-wl-unicode \
    --field=operator-to-ascii \
    --field=operator-to-unicode \
    -o op-tables.json
mathics3-generate-operator-json-table -o operator-tables.json
```

Oh, and by the way, use `pip install -e .[dev]` when installing from git so you get the packages needed for testing, i.e. pytest.

I will try to update https://mathics-development-guide.readthedocs.io/en/latest/installing.html#install-from-the-mathics3-github-organization, but if you want to make corrections to that repository, please do.

**Comment by ricor07** [comment]
Are you sure these are windows commands? Command prompt does not recognize mathics3-generate-json-table and so on

**Comment by rocky** [comment]
> Are you sure these are windows commands? Command prompt does not recognize mathics3-generate-json-table and so on

Ah, you have to also install `mathics-scanner` from github sources. Occasionally as we improve things the API between the scanner and mathics core changes and when that happens, you have to build both from source. 

mathics3-generate-json-table and  mathics3-generate-json-table](https://github.com/Mathics3/mathics-scanner/blob/master/pyproject.toml#L56-L57) are new scripts that are installed when you install `mathics-scanner` from the github master branch.

**Comment by rocky** [comment]
And BTW when https://github.com/Mathics3/mathics-scanner/pull/111 goes in, more information additional information in the JSON tables will be added and so this process will be needed to be done again. 

One of the reasons we haven't made a new release, is that we want to minimize this kind of stuff for non-developers. So when we break the API as we do here, we try to batch in all the breaking changes to reduce this kind of annoyance.

**Comment by ad-si** [comment]
FYI: I added extensive support for this in Woxi starting in https://github.com/ad-si/Woxi/commit/e0bf388 and following commits.

Playground example:
http://localhost:5501/playground/index.html?code=EoUwZglgdiDaDKBHATgF1gDwHoCYC6ANAAQZEB8RADHgFCiQwIrrb7GkA6sAogDYgBbEFFR4ioAIa8AzrQCC06QFcB0AOaZyAXipEAZHqIBPIgB4qxAJJhYAFWRKQARVj1ocUgFpj5KnkLi4O5MaJi4xrj%2BxNS0bowAFNgAzACUWPEAjAD0qezafnRBCRJYAEZpAMbEnhlmRKV1GbFFcCUADvVYbcQSvpT6hg0U1IUMcAAyAPYaGAGk5iNxE9NhbQE1dR3mTaPB8NCwANZEAAoQAXyCwuiHViIgaiDIss1jsADCk9KaANREx2cLvwhCIjndUA8ni9dow5MgKrYJFA7EjMFEiJ4zlkcHVQGi6lj8DDWuFvKVwn9alodJQekQ-g1qQUlrASjjvL0GgzwmQacRLiD0L0AD71YiSGT%2BYmwRIYogZNI4v7xEzeHCKupJbHsCkRHGmHQ7FkC64ynGkP7YNopLKygDiEgEAgkvyI%2BBS4pAUlkeWGAyIHWGr2CJtBOMOWCSRAAYrxJpNkGisLciJZ7o9nkCrqCU2mIRnZP7jn6DERQyxPd6pSzY-HEzjepSs4LWeDIZng4x3iAILx1GjiPqSGYdElO3Bo8gJBVUBBJlApCcJKEJAFegt-QBZSYAE1b8rETOyY%2Bl273EmIABZm6b4o2iKkspe2wXqy1XK16fVUzfQSKxYEVbjggEBqMirByqQJh-EYupNPywKmqQopGJWkp4EAA

**Comment by rocky** [comment]
> FYI: I added extensive support for this in Woxi starting in [ad-si/Woxi@e0bf388](https://github.com/ad-si/Woxi/commit/e0bf388) and following commits.
> 
Thanks. I'll look at this when I get the time. And for Vectorless, AlphabeticOrder, Distribute, Interval, PartitionsQ, BellY, etc.?
