### ISSUE TITLE
Crash during FullSimplify

### ISSUE THREAD

**Issue by hrueter** [Mathics3/mathics-core#214]
### Observed behavior
Mathics crashes from the following input
```
In[1]:= a[x] + e f / (2 d) + c[x] // FullSimplify
```
### Expected behavior
```
In[1]:= a[x] + e f / (2 d) + c[x] // FullSimplify
Out[1]= e f / (2 d) + a[x] + c[x]
```
### Background
I tried to find a more minimal example, but reducing the input further eliminates the failure.

Curiously the following order of input works
```
In[1]:= a[x] + e f / (d) + c[x] // FullSimplify
Out[1]= e f / d + a[x] + c[x]

In[2]:= a[x] + e f / (2 d) + c[x] // FullSimplify
Out[2]= e f / (2 d) + a[x] + c[x]
```

### Setup
Linux Mint 20.3
Mathics 4.0.0 on CPython 3.8.10 (default, Nov 26 2021, 20:14:08)  using SymPy 1.8, mpmath 1.2.1, numpy 1.17.4

### Traceback
```
Traceback (most recent call last):
  File "/usr/local/bin/mathics", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/mathics/main.py", line 402, in main
    result = evaluation.evaluate(query, timeout=settings.TIMEOUT)
  File "/usr/local/lib/python3.8/dist-packages/mathics/core/evaluation.py", line 361, in evaluate
    result = run_with_timeout_and_stack(evaluate, timeout, self)
  File "/usr/local/lib/python3.8/dist-packages/mathics/core/evaluation.py", line 118, in run_with_timeout_and_stack
    return request()
  File "/usr/local/lib/python3.8/dist-packages/mathics/core/evaluation.py", line 332, in evaluate
    self.last_eval = query.evaluate(self)
  File "/usr/local/lib/python3.8/dist-packages/mathics/core/expression.py", line 1315, in evaluate
    expr, reevaluate = expr.evaluate_next(evaluation)
  File "/usr/local/lib/python3.8/dist-packages/mathics/core/expression.py", line 1449, in evaluate_next
    result = rule.apply(new, evaluation, fully=False)
  File "/usr/local/lib/python3.8/dist-packages/mathics/core/rules.py", line 67, in apply
    self.pattern.match(yield_match, expression, {}, evaluation, fully=fully)
  File "/usr/local/lib/python3.8/dist-packages/mathics/core/pattern.py", line 291, in match
    self.head.match(yield_head, expression.get_head(), vars, evaluation)
  File "/usr/local/lib/python3.8/dist-packages/mathics/core/pattern.py", line 159, in match
    yield_func(vars, None)
  File "/usr/local/lib/python3.8/dist-packages/mathics/core/pattern.py", line 281, in yield_head
    self.get_pre_choices(
  File "/usr/local/lib/python3.8/dist-packages/mathics/core/pattern.py", line 429, in get_pre_choices
    yield_func(vars)
  File "/usr/local/lib/python3.8/dist-packages/mathics/core/pattern.py", line 258, in yield_choice
    self.match_leaf(
  File "/usr/local/lib/python3.8/dist-packages/mathics/core/pattern.py", line 655, in match_leaf
    self.get_wrappings(
  File "/usr/local/lib/python3.8/dist-packages/mathics/core/pattern.py", line 456, in get_wrappings
    yield_func(items[0])
  File "/usr/local/lib/python3.8/dist-packages/mathics/core/pattern.py", line 643, in yield_wrapping
    leaf.match(
  File "/usr/local/lib/python3.8/dist-packages/mathics/builtin/patterns.py", line 852, in match
    self.pattern.match(yield_func, expression, new_vars, evaluation)
  File "/usr/local/lib/python3.8/dist-packages/mathics/builtin/patterns.py", line 1050, in match
    yield_func(vars, None)
  File "/usr/local/lib/python3.8/dist-packages/mathics/core/pattern.py", line 640, in match_yield
    yield_func(new_vars, items_rest)
  File "/usr/local/lib/python3.8/dist-packages/mathics/core/rules.py", line 42, in yield_match
    new_expression = self.do_replace(expression, vars, options, evaluation)
  File "/usr/local/lib/python3.8/dist-packages/mathics/core/rules.py", line 131, in do_replace
    return self.function(evaluation=evaluation, **vars_noctx)
  File "/usr/local/lib/python3.8/dist-packages/mathics/builtin/numbers/algebra.py", line 424, in apply
    sympy_result = sympy.simplify(sympy_expr)
  File "/usr/local/lib/python3.8/dist-packages/sympy/simplify/simplify.py", line 757, in simplify
    return done(expr)
  File "/usr/local/lib/python3.8/dist-packages/sympy/simplify/simplify.py", line 576, in done
    rv = e.doit() if doit else e
  File "/usr/local/lib/python3.8/dist-packages/sympy/core/operations.py", line 432, in doit
    terms = [term.doit(**hints) for term in self.args]
  File "/usr/local/lib/python3.8/dist-packages/sympy/core/operations.py", line 432, in <listcomp>
    terms = [term.doit(**hints) for term in self.args]
  File "/usr/local/lib/python3.8/dist-packages/sympy/core/basic.py", line 1668, in doit
    return self.func(*terms)
  File "/usr/local/lib/python3.8/dist-packages/mathics/core/convert.py", line 65, in __new__
    return SympyExpression(self.expr)
AttributeError: 'SympyExpression' object has no attribute 'expr'

```

**Comment by TiagoCavalcante** [comment]
@mmatera @rocky a good part of convert.py needs to be re-written, this is the output with the branch fix-214: `e f / (2 d) + SympyExpression[SympyExpression, a, x] + SympyExpression[SympyExpression, c, x]`

Some parts are converted to Sympy and others don't.

Also, the SympyExpression class is very fragile as the property `expr` may be undefined (and this bug is an example of this happening).

**Comment by TiagoCavalcante** [comment]
Fixed by PR #232.

**Comment by hrueter** [comment]
In fact this issue was not fixed by #232. Please reopen the issue.

**Comment by TiagoCavalcante** [comment]
@hrueter latest master commit:
![image](https://user-images.githubusercontent.com/62714153/159520501-2bbbc8c1-9d8e-49dd-b270-a41f3d490286.png)

**Comment by mmatera** [comment]
I still see the traceback...

**Comment by rocky** [comment]
And what version of SymPy are you running?
