### ISSUE TITLE
Session without builtins not working

### ISSUE THREAD

**Issue by TiagoCavalcante** [Mathics3/mathics-core#26]
Some things you try to evaluate in a session without builtins aren't working.

e.g.:
```py
>>> from mathics.session import MathicsSession
>>> session = MathicsSession(add_builtin=False)
>>> session.evaluate("x")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/src/app/mathics-core/mathics/session.py", line 65, in evaluate
    expr = parse(self.definitions, MathicsSingleLineFeeder(str_expression))
  File "/usr/src/app/mathics-core/mathics/core/parser/util.py", line 21, in parse
    return parse_returning_code(definitions, feeder)[0]
  File "/usr/src/app/mathics-core/mathics/core/parser/util.py", line 34, in parse_returning_code
    return convert(ast, definitions), source_code
  File "/usr/src/app/mathics-core/mathics/core/parser/convert.py", line 165, in convert
    result = self.do_convert(node)
  File "/usr/src/app/mathics-core/mathics/core/parser/convert.py", line 171, in do_convert
    return getattr(self, "_make_" + result[0])(*result[1:])
  File "/usr/src/app/mathics-core/mathics/core/parser/convert.py", line 177, in _make_Lookup
    value = self.definitions.lookup_name(s)
  File "/usr/src/app/mathics-core/mathics/core/definitions.py", line 383, in lookup_name
    current_context = self.get_current_context()
  File "/usr/src/app/mathics-core/mathics/core/definitions.py", line 256, in get_current_context
    context = context_rule.replace.get_string_value()
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by TiagoCavalcante** [comment]
Seems that `System`$Context` is undefined.

**Comment by rocky** [comment]
It may take a little work, but I suspect there is a way to load in only a very small set of builtins. See Mathics3/mathics-core/mathics/builtin/__init__.py for code that you'd need to modify to load in some builtins.

**Comment by rocky** [comment]
Another approach would be to load in _all_ builtins but then start removing some.

**Comment by mmatera** [comment]
A drastic way to avoid loading builtins is just to delete the non-essential modules.  Then, what you get is what I would like to call "mathics-core". 
In any case, to have a very large definition dictionary shouldn't be a problem if the keys are handled efficiently.

**Comment by TiagoCavalcante** [comment]
> In any case, to have a very large definition dictionary shouldn't be a problem if the keys are handled efficiently.

@mmatera I believe the keys aren't the problem, I think the bigger problem is that when we type `x` it isn't only searching for `x`, it may also be searching by `Format[x]`, so it needs to check in the `OwnValues` dict of `Format` too.

**Comment by mmatera** [comment]
Format happens just at the end of the evaluation, and over a (relatively small) number of symbols. Actually, using Mathicssession you can avoid the formatting step if you want to know what is exactly the overhead.

**Comment by TiagoCavalcante** [comment]
Fixed by @mmatera.
