### ISSUE TITLE
Requirement for pillow<10.1.0 makes mathics fail to launch - Arch Linux

### ISSUE THREAD

**Issue by coxackie** [Mathics3/mathics-core#936]
## Description

 In `mathics` latest 6.0.3 version, there is a requirement for `pillow<10.1.0`. Arch Linux ships pillow 10.1.0. This has the effect that `mathics` does not launch, failing the requirements check. See https://github.com/chaotic-aur/packages/issues/2915#issuecomment-1821774260 for more information. As pointed out to that ticket, deleting `/usr/lib/python3.11/site-packages/Mathics3-6.0.3-py3.11.egg-info/requires.txt` makes `mathics` work. It would be preferable to remove the restriction on pillow, of course, unless there is a serious blocker.

## How to Reproduce

Steps to reproduce the behavior.

1. Build `mathics` from the AUR in Arch Linux.
2. Try to launch it.
3. Fail.

## Output Given

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 631, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 875, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Pillow 10.1.0 (/usr/lib/python3.11/site-packages), Requirement.parse('pillow<10.1.0,>=8.3.2'), {'imageio'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mathics", line 33, in <module>
    sys.exit(load_entry_point('Mathics3==6.0.3', 'console_scripts', 'mathics')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/mathics", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/mathics/main.py", line 13, in <module>
    from mathics import __version__, license_string, settings, version_string
  File "/usr/lib/python3.11/site-packages/mathics/settings.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3327, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3302, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3340, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 633, in _build_master
    return cls._build_from_requirements(__requires__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 646, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 875, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Pillow 10.1.0 (/usr/lib/python3.11/site-packages), Requirement.parse('pillow<10.1.0,>=8.3.2'), {'imageio'})
```

## Expected behavior

`mathics` launches, instead of failing miserably to launch.

## Your Environment

**All: Mathics 6.0.3.

In addition

**Desktop (please complete the following information):**
 - OS: Arch Linux

## Workarounds

Delete `/usr/lib/python3.11/site-packages/Mathics3-6.0.3-py3.11.egg-info/requires.txt`.

**Comment by rocky** [comment]
I will put out another (6.0.4) release this weekend and will try to address this. 

I have no problem (after trying this out) adding a requirement that Pillow be `<10.1.0` .

However note that https://github.com/Mathics3/mathics-core/blob/relesae-6.0.4/setup.py and the same for 6.03 (I will fix the spelling of "release" the branch name of 6.04) do not claim to support 3.11. 

Probably safest in the 6.0.4 release _not_ to change that.  If it _happens_ to work on 3.11, that of course is okay.

Sometime after the first week of 2024 we will come out with a 7.x release, and that can mention 3.11 (and possibly 3.12) Python 3.6 support will be dropped and as the version number suggests there are massive API changes.

Also, as best as I can tell, PYPI no longer supports eggs, so the 6.03 did not include an egg, and the next release will not have an egg, but just a wheel and source tar'd gzip.

**Comment by coxackie** [comment]
Thanks a lot for this, no problem about "not claiming to support `python` 3.11". Just a clarification: you write that you "have no problem (after trying this out) adding a requirement that Pillow be <10.1.0". In fact, one should _drop_ the requirement that Pillow be <10.1.0, not add it (it is already there, and it is exactly this that is the problem).

**Comment by rocky** [comment]
Hmmm.  https://github.com/Mathics3/mathics-core/blob/relesae-6.0.4/setup.py  does not have anything about Pillow being < 10.1.0. So where in the code do you see this?

**Comment by xiota** [comment]
The seems to be the way the package is created.  The `egg-info/requires.txt` file is somehow generated by `setup.py` when the package is installed with the following commands:
```bash
python setup.py build
python setup.py install --root="${pkgdir}" --optimize=1 --skip-build
```

But switching to PEP517 install does not produce the problem file.
```bash
python -m build --no-isolation --wheel
python -m installer --destdir="${pkgdir:?}" dist/*.whl
```

**Comment by rocky** [comment]
So do I have it correct that nothing needs to be done in this repository?

**Comment by coxackie** [comment]
That is correct, I am closing this. (If it turns out that we discover something else, I will inform you.) Thank you very much for your time and patience.
