### ISSUE TITLE
Running under Android ARM64 via Termux

### ISSUE THREAD

**Issue by defencedog** [Mathics3/mathics-core#960]
It runs OK, however when i initiate it it provides weird error
```
~ $ mathicsscript
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/psutil/_common.py", line 398, in wrapper
    return cache[key]
KeyError: (('/proc',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/psutil/_pslinux.py", line 285, in <module>
    set_scputimes_ntuple("/proc")
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/psutil/_common.py", line 400, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/psutil/_pslinux.py", line 268, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/psutil/_common.py", line 727, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
PermissionError: [Errno 13] Permission denied: '/proc/stat'
Cannot find setting named 'lsp'

Mathicscript: 6.0.0, Mathics 6.0.4
on CPython 3.9.18 (main, Sep  8 2023, 11:55:57)

Using:
SymPy 1.11.1, mpmath 1.2.1, numpy 1.23.4
cython 3.0.8, matplotlib 3.6.0,
Asymptote version 2.86

Copyright (C) 2011-2023 The Mathics Team.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.
See the documentation for the full license.

Quit by evaluating Quit[] or by pressing CONTROL-D.

In[1]:=
```

**Comment by defencedog** [comment]
It is of no consequence. On `termux` you cannot `sudo`. I followed this:

create this dir structure `~/.local/var/mathics`
```
cd ~/.local/var/mathics/
wget https://raw.githubusercontent.com/Mathics3/mathics-omnibus/master/docker/django-db/mathics.sqlite
python -c 'import site; print(site.getsitepackages())'
cd /data/data/com.termux/files/usr/lib/python3.9/site-packages/mathics_django
MATHICS_DJANGO_DB_PATH=/data/data/com.termux/files/home/.local/var/mathics/mathics.sqlite  python manage.py runserver
```
![SmartSelect_20240112_005346_Orions Browser](https://github.com/Mathics3/mathics-core/assets/831749/f5a067c8-7940-4777-be8a-2e746a59e6d7)

**Comment by rocky** [comment]
Thanks for the information. I will try to update install docs See https://mathics-development-guide.readthedocs.io/en/latest/ 

Or feel free to suggest changes and submit that in https://github.com/Mathics3/mathics-development-guide . Thanks in advance.

**Comment by defencedog** [comment]
Complete guide I followed:


`pkg i asymptote mariadb`
`pip list | grep mathic`
Mathics-Django                     6.0.0
mathics-pygments                   1.0.2
Mathics-Scanner                    1.3.0
Mathics3                           6.0.4
mathicsscript                      6.0.0

```
Mathicscript: 6.0.0, Mathics 6.0.4
on CPython 3.9.18 (main, Sep  8 2023, 11:55:57)
Using:
SymPy 1.11.1, mpmath 1.2.1, numpy 1.23.4
cython 3.0.8, matplotlib 3.6.0,
Asymptote version 2.86

pip install Mathics-Scanner
pip install Mathics3
pip install Mathics-Django[full]
pip install mathics-pygments
wget https://github.com/Mathics3/mathicsscript/releases/download/6.0.0/mathicsscript-6.0.0-py3-none-any.whl
pip install mathicsscript-6.0.0-py3-none-any.whl
```

**Using webserver**
https://github.com/Mathics3/mathics-core/issues/960#issuecomment-1888040307
create this dir structure
```
cd ~/.local/var/mathics/
wget https://raw.githubusercontent.com/Mathics3/mathics-omnibus/master/docker/django-db/mathics.sqlite
```
now simply run mathicsserver
It will autoregister .sqlite
OR
```
python -c 'import site; print(site.getsitepackages())'
cd /data/data/com.termux/files/usr/lib/python3.9/site-packages/mathics_django
MATHICS_DJANGO_DB_PATH=/data/data/com.termux/files/home/.local/var/mathics/mathics.sqlite  python manage.py runserver
```
Temrinal results are OK
```
database initialized sucessfully

Django front end version 6.0.0
Mathics 6.0.4
on CPython 3.9.18 (main, Sep  8 2023, 11:55:57)
using SymPy 1.11.1, mpmath 1.2.1, django 4.2.9, cython 3.0.8

Copyright (C) 2011-2023 The Mathics Team.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.
See the documentation for the full license.

Quit by pressing CONTROL-C

Open the graphical user interface at
http://localhost:8000/
in Firefox, Chrome, or Safari to use Mathics
```

**Comment by defencedog** [comment]
@rocky  we need some youtube videos please

**Comment by rocky** [comment]
Actually, you are in a better position to do one for doing this on Android ARM64! :-)

**Comment by defencedog** [comment]
@rocky I meant tutorial videos. Regarding compiling it's straightforward no video required. Twrmux community is big....

**Comment by rocky** [comment]
> Regarding compiling it's straightforward no video required. 

It may be straightforward for you, but certainly not for me!  And that is kind of a truism here. Things that you don't understand you'd like (someone else) do additional work for, while overlooking the fact that there are ways that you can contribute that might help _others_. 

This project underfunded and understaffed.  So please consider contributing in some way.

**Comment by defencedog** [comment]
OK I will do that.
